version: '3.8'

services:
  cb-ide:
    image: terrydhariwal/cb-ide:v1.0
    ports:
      - "80:3000"
#    volumes:
#      - ./workspace:/home/project
#      - ./m2:/home/theia/.m2
#      - ./home/theia:/home/theia/
    depends_on:
      - nexus
    networks:
      - cleverbits_net

  # https://hub.docker.com/r/sonatype/nexus3/#user-content-persistent-data
  nexus:
    image: sonatype/nexus3
    ports:
      - "443:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - cleverbits_net

networks:
  cleverbits_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 800

volumes:
  nexus-data:
