version: '3.8'

services:
  cb-ide:
    image: terrydhariwal/cb-ide:v2.0
    ports:
      - "80:3000"
    volumes:
      - theia-home:/home/theia/
      - theia-workspace:/home/project
#      - ./m2:/home/theia/.m2

    depends_on:
      - nexus
    networks:
      - cleverbits_net

  # https://hub.docker.com/r/sonatype/nexus3/#user-content-persistent-data
  nexus:
    image: sonatype/nexus3
    ports:
      - "443:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - cleverbits_net

networks:
  cleverbits_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 800

volumes:
  nexus-data:
  theia-home:
  theia-workspace:
